
public class Question3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Coin a =new Coin();
		System.out.println(a.toString());
		

	}

}
class Coin {
	int flipcoin;
	String face;
	/*
	 * This method randomly generates a coin flip 
	 * pre: none
	 * post: returns the coin face generated by flipcoin (heads/tail)
	 */
	public int flipCoin() {
		flipcoin = (int)Math.round(Math.random());
		return flipcoin;
	}
	
	/*
	 * This methods returns the flipcoin
	 * pre: none
	 * post: returns face generated from flipCoin method
	 */
	public String toString () {
		String face;
		if (flipcoin == 0)
			face = "Tails up";
		else 
			face = "Heads up";
		
		return face;
	}
}